from sqlalchemy import (
    Column, Integer, String, Boolean, DateTime, Numeric, ForeignKey
)
from sqlalchemy.orm import declarative_base

Base = declarative_base()

class Order(Base):
    __tablename__ = "Orders"

    OrderId = Column(String(30), primary_key=True)
    MOHeaderId = Column(Integer, ForeignKey("MoHeader.MOHeaderId"), nullable=False)
    MOId = Column(Integer)
    MOSalesforceId = Column(String(18))
    SOHeaderID = Column(Integer, ForeignKey("SoHeader.SOHeaderID"), nullable=False)
    SOId = Column(String(20))
    SOSalesforceId = Column(String(18))
    CustomerId = Column(Integer, ForeignKey("Users.UserId"), nullable=False)
    SoldToId = Column(Integer, ForeignKey("SoldTo.SoldToId"), nullable=False)
    ShippingaddressId = Column(Integer, ForeignKey("ShippingAddress.ShippingAddressId"), nullable=False)
    ProductId = Column(Integer, ForeignKey("Product.ProductId"), nullable=False)
    ContactId = Column(Integer, ForeignKey("Contact.ContactId"), nullable=False)
    ShippingMethodId = Column(Integer, ForeignKey("ShippingMethod.ShippingMethodId"), nullable=False)
    OrderTypeId = Column(Integer, ForeignKey("OrderType.OrderTypeId"), nullable=False)
    GumTypeId = Column(Integer, ForeignKey("GumType.GumTypeId"), nullable=False)
    MasterQtyDimTypesId = Column(Integer, ForeignKey("MasterQtyDimTypes.MasterQtyDimTypesId"), nullable=False)
    QuoteReferenceId = Column(Integer, ForeignKey("QuoteReference.QuoteReferenceId"), nullable=False)
    UMId = Column(Integer, ForeignKey("UM.UMId"), nullable=False)
    CSRId_OrderTakenBy = Column(Integer, ForeignKey("CSR.CSRId"), nullable=False)
    CSRId_CheckedBy = Column(String(10))
    CSRId_RevisedBy = Column(String(10))
    SetUpCharges = Column(Numeric(12, 3))
    AdhesiveChangeCharges = Column(Numeric(12, 3))
    LateOrder = Column(Boolean)
    Reason = Column(String(500))
    SpecialInstructions = Column(String(8000))
    LineNumber = Column(String(5), nullable=False)
    Notes = Column(String(8000))
    PrevMO = Column(Integer)
    ApplicationProfileCompleted = Column(Boolean, nullable=False)
    CustomerRequestDate = Column(DateTime)
    PONumber = Column(String(15), nullable=False)
    ShipDate = Column(DateTime)
    OrderDate = Column(DateTime)
    Location = Column(String(100))
    IsDeleted = Column(Boolean, nullable=False)
    CreatedOn = Column(DateTime, nullable=False)
    CreatedBy = Column(Integer, ForeignKey("Users.UserId"), nullable=False)
    ModifiedBy = Column(Integer, ForeignKey("Users.UserId"))
    ModifiedOn = Column(DateTime)
    OrderStatusId = Column(Integer, ForeignKey("OrderStatus.OrderStatusId"), nullable=False)